/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    pages: Page;
    media: Media;
    testimonials: Testimonial;
    faqs: Faq;
    'process-steps': ProcessStep;
    projects: Project;
    categories: Category;
    services: Service;
    packages: Package;
    availability: Availability;
    inquiries: Inquiry;
    posts: Post;
    'post-categories': PostCategory;
    users: User;
    'payload-kv': PayloadKv;
    'payload-jobs': PayloadJob;
    'payload-folders': FolderInterface;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {
    'payload-folders': {
      documentsAndFolders: 'payload-folders' | 'media';
    };
  };
  collectionsSelect: {
    pages: PagesSelect<false> | PagesSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    testimonials: TestimonialsSelect<false> | TestimonialsSelect<true>;
    faqs: FaqsSelect<false> | FaqsSelect<true>;
    'process-steps': ProcessStepsSelect<false> | ProcessStepsSelect<true>;
    projects: ProjectsSelect<false> | ProjectsSelect<true>;
    categories: CategoriesSelect<false> | CategoriesSelect<true>;
    services: ServicesSelect<false> | ServicesSelect<true>;
    packages: PackagesSelect<false> | PackagesSelect<true>;
    availability: AvailabilitySelect<false> | AvailabilitySelect<true>;
    inquiries: InquiriesSelect<false> | InquiriesSelect<true>;
    posts: PostsSelect<false> | PostsSelect<true>;
    'post-categories': PostCategoriesSelect<false> | PostCategoriesSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-jobs': PayloadJobsSelect<false> | PayloadJobsSelect<true>;
    'payload-folders': PayloadFoldersSelect<false> | PayloadFoldersSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    'site-settings': SiteSetting;
    about: About;
  };
  globalsSelect: {
    'site-settings': SiteSettingsSelect<false> | SiteSettingsSelect<true>;
    about: AboutSelect<false> | AboutSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: {
      schedulePublish: TaskSchedulePublish;
      inline: {
        input: unknown;
        output: unknown;
      };
    };
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * Every page is built from sections. Add, remove, reorder (drag) and switch sections on/off. The page with slug “home” is the homepage.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: number;
  title: string;
  layout?:
    | (
        | HeroBlock
        | PageHeaderBlock
        | IntroBlock
        | FeaturedPortfolioBlock
        | FeaturedStoryBlock
        | ServicesBlock
        | PricingBlock
        | ProcessBlock
        | TestimonialsBlock
        | FaqBlock
        | AvailabilityBlock
        | ContactBlock
        | InstagramBlock
        | AboutBlock
        | RichTextBlock
        | ImageBannerBlock
        | CtaBlock
        | PortfolioIndexBlock
        | JournalListBlock
        | GalleryBlock
      )[]
    | null;
  meta?: {
    title?: string | null;
    description?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Media;
    /**
     * Defaults to the meta title.
     */
    ogTitle?: string | null;
    /**
     * Defaults to the meta description.
     */
    ogDescription?: string | null;
    /**
     * Only if this content lives primarily at another address. Leave empty normally.
     */
    canonical?: string | null;
    noIndex?: boolean | null;
  };
  /**
   * The address of this page. Leave empty to generate it from the title.
   */
  slug?: string | null;
  excludeFromSitemap?: boolean | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "HeroBlock".
 */
export interface HeroBlock {
  enabled?: boolean | null;
  tone?: ('light' | 'sand' | 'dark') | null;
  /**
   * Optional ID for links like /#pricing
   */
  anchor?: string | null;
  /**
   * One image, or several for a slow cross-fading slideshow. Drag to reorder.
   */
  slides: (number | Media)[];
  /**
   * Small label above the heading
   */
  eyebrow?: string | null;
  heading: string;
  subheading?: string | null;
  primaryCta?: {
    label?: string | null;
    /**
     * e.g. /contact, /portfolio or https://…
     */
    url?: string | null;
  };
  secondaryCta?: {
    label?: string | null;
    /**
     * e.g. /contact, /portfolio or https://…
     */
    url?: string | null;
  };
  height?: ('full' | 'tall') | null;
  /**
   * Darkening over the photo (0–80%) for text readability
   */
  overlay?: number | null;
  /**
   * Seconds per slide
   */
  interval?: number | null;
  showScrollIndicator?: boolean | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'hero';
}
/**
 * Upload photographs here (drag & drop several at once). Images are compressed automatically and responsive sizes are generated.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  /**
   * Describe the image for screen readers and Google, e.g. "Bride and groom walking in Djurgården at sunset".
   */
  alt: string;
  title?: string | null;
  /**
   * Optional caption shown under the image on the website.
   */
  caption?: string | null;
  /**
   * Internal notes / longer description.
   */
  description?: string | null;
  blurDataURL?: string | null;
  _objectKey?: string | null;
  folder?: (number | null) | FolderInterface;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumb?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    medium?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    large?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    og?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-folders".
 */
export interface FolderInterface {
  id: number;
  name: string;
  folder?: (number | null) | FolderInterface;
  documentsAndFolders?: {
    docs?: (
      | {
          relationTo?: 'payload-folders';
          value: number | FolderInterface;
        }
      | {
          relationTo?: 'media';
          value: number | Media;
        }
    )[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  folderType?: 'media'[] | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "PageHeaderBlock".
 */
export interface PageHeaderBlock {
  enabled?: boolean | null;
  tone?: ('light' | 'sand' | 'dark') | null;
  /**
   * Optional ID for links like /#pricing
   */
  anchor?: string | null;
  /**
   * Small label above the heading
   */
  eyebrow?: string | null;
  heading: string;
  text?: string | null;
  /**
   * Optional full-width image
   */
  image?: (number | null) | Media;
  id?: string | null;
  blockName?: string | null;
  blockType: 'pageHeader';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "IntroBlock".
 */
export interface IntroBlock {
  enabled?: boolean | null;
  tone?: ('light' | 'sand' | 'dark') | null;
  /**
   * Optional ID for links like /#pricing
   */
  anchor?: string | null;
  /**
   * Small label above the heading
   */
  eyebrow?: string | null;
  heading?: string | null;
  text?: string | null;
  /**
   * Leave empty to use the portrait from “About the photographer”.
   */
  image?: (number | null) | Media;
  secondaryImage?: (number | null) | Media;
  cta?: {
    label?: string | null;
    /**
     * e.g. /contact, /portfolio or https://…
     */
    url?: string | null;
  };
  id?: string | null;
  blockName?: string | null;
  blockType: 'intro';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FeaturedPortfolioBlock".
 */
export interface FeaturedPortfolioBlock {
  enabled?: boolean | null;
  tone?: ('light' | 'sand' | 'dark') | null;
  /**
   * Optional ID for links like /#pricing
   */
  anchor?: string | null;
  /**
   * Small label above the heading
   */
  eyebrow?: string | null;
  heading?: string | null;
  text?: string | null;
  mode?: ('featured' | 'selected' | 'category') | null;
  projects?: (number | Project)[] | null;
  category?: (number | null) | Category;
  limit?: number | null;
  showCategories?: boolean | null;
  cta?: {
    label?: string | null;
    /**
     * e.g. /contact, /portfolio or https://…
     */
    url?: string | null;
  };
  id?: string | null;
  blockName?: string | null;
  blockType: 'featuredPortfolio';
}
/**
 * Every wedding, portrait session or commission. Each project is shown as an immersive photo story. Drag to reorder.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "projects".
 */
export interface Project {
  id: number;
  _order?: string | null;
  /**
   * e.g. "Anna & Erik"
   */
  title: string;
  /**
   * e.g. Stockholm
   */
  location?: string | null;
  date?: string | null;
  /**
   * One or two sentences used on cards and at the start of the story.
   */
  excerpt?: string | null;
  cover: number | Media;
  /**
   * Select or bulk-upload photographs and drag to reorder. The editorial layout is composed automatically from each image’s shape. Captions & alt text come from the media library.
   */
  gallery?: (number | Media)[] | null;
  /**
   * Short storytelling passages placed between the photographs.
   */
  chapters?:
    | {
        heading?: string | null;
        text: string;
        /**
         * Place this passage after photograph number… (0 = before the first photograph)
         */
        afterImage?: number | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Optional credits, e.g. Venue, Planner, Florist.
   */
  credits?:
    | {
        role: string;
        name: string;
        id?: string | null;
      }[]
    | null;
  meta?: {
    title?: string | null;
    description?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Media;
    /**
     * Defaults to the meta title.
     */
    ogTitle?: string | null;
    /**
     * Defaults to the meta description.
     */
    ogDescription?: string | null;
    /**
     * Only if this content lives primarily at another address. Leave empty normally.
     */
    canonical?: string | null;
    noIndex?: boolean | null;
  };
  /**
   * The address of this page. Leave empty to generate it from the title.
   */
  slug?: string | null;
  category?: (number | null) | Category;
  /**
   * Show in the featured portfolio on the homepage.
   */
  featured?: boolean | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * e.g. Weddings, Portraits, Couples. Each category gets its own portfolio page. Drag to reorder.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories".
 */
export interface Category {
  id: number;
  _order?: string | null;
  title: string;
  /**
   * Small line above the heading, e.g. "Wedding photography · Stockholm"
   */
  eyebrow?: string | null;
  description?: string | null;
  cover?: (number | null) | Media;
  meta?: {
    title?: string | null;
    description?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Media;
    /**
     * Defaults to the meta title.
     */
    ogTitle?: string | null;
    /**
     * Defaults to the meta description.
     */
    ogDescription?: string | null;
    /**
     * Only if this content lives primarily at another address. Leave empty normally.
     */
    canonical?: string | null;
    noIndex?: boolean | null;
  };
  /**
   * The address of this page. Leave empty to generate it from the title.
   */
  slug?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FeaturedStoryBlock".
 */
export interface FeaturedStoryBlock {
  enabled?: boolean | null;
  tone?: ('light' | 'sand' | 'dark') | null;
  /**
   * Optional ID for links like /#pricing
   */
  anchor?: string | null;
  /**
   * Small label above the heading
   */
  eyebrow?: string | null;
  project: number | Project;
  /**
   * Leave empty to use the project title.
   */
  headingOverride?: string | null;
  /**
   * Leave empty to use the project introduction.
   */
  textOverride?: string | null;
  imageCount?: number | null;
  ctaLabel?: string | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'featuredStory';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ServicesBlock".
 */
export interface ServicesBlock {
  enabled?: boolean | null;
  tone?: ('light' | 'sand' | 'dark') | null;
  /**
   * Optional ID for links like /#pricing
   */
  anchor?: string | null;
  /**
   * Small label above the heading
   */
  eyebrow?: string | null;
  heading?: string | null;
  text?: string | null;
  mode?: ('all' | 'selected') | null;
  services?: (number | Service)[] | null;
  cta?: {
    label?: string | null;
    /**
     * e.g. /contact, /portfolio or https://…
     */
    url?: string | null;
  };
  id?: string | null;
  blockName?: string | null;
  blockType: 'services';
}
/**
 * Each service gets a card on the website and its own dedicated page. Drag to reorder.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "services".
 */
export interface Service {
  id: number;
  _order?: string | null;
  title: string;
  /**
   * Shown on the service card.
   */
  excerpt?: string | null;
  image?: (number | null) | Media;
  /**
   * e.g. "From 24 000 SEK"
   */
  startingPrice?: string | null;
  /**
   * e.g. "incl. VAT"
   */
  priceNote?: string | null;
  description?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  features?:
    | {
        text: string;
        id?: string | null;
      }[]
    | null;
  gallery?: (number | Media)[] | null;
  /**
   * Show recent projects from this portfolio category on the service page.
   */
  relatedCategory?: (number | null) | Category;
  /**
   * Cities/regions where you offer this service, e.g. Stockholm, Uppsala, Gotland.
   */
  areas?:
    | {
        name: string;
        id?: string | null;
      }[]
    | null;
  ctaLabel?: string | null;
  /**
   * Leave empty to link to the contact form.
   */
  ctaUrl?: string | null;
  meta?: {
    title?: string | null;
    description?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Media;
    /**
     * Defaults to the meta title.
     */
    ogTitle?: string | null;
    /**
     * Defaults to the meta description.
     */
    ogDescription?: string | null;
    /**
     * Only if this content lives primarily at another address. Leave empty normally.
     */
    canonical?: string | null;
    noIndex?: boolean | null;
  };
  /**
   * The address of this page. Leave empty to generate it from the title.
   */
  slug?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "PricingBlock".
 */
export interface PricingBlock {
  enabled?: boolean | null;
  tone?: ('light' | 'sand' | 'dark') | null;
  /**
   * Optional ID for links like /#pricing
   */
  anchor?: string | null;
  /**
   * Small label above the heading
   */
  eyebrow?: string | null;
  heading?: string | null;
  text?: string | null;
  mode?: ('all' | 'selected') | null;
  packages?: (number | Package)[] | null;
  /**
   * Small print under the packages.
   */
  footnote?: string | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'pricing';
}
/**
 * Create, reorder (drag) and edit your packages. The button opens the contact form with this package pre-selected.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "packages".
 */
export interface Package {
  id: number;
  _order?: string | null;
  /**
   * e.g. Essential, Signature, Full day
   */
  name: string;
  /**
   * e.g. "For intimate ceremonies"
   */
  tagline?: string | null;
  description?: string | null;
  /**
   * e.g. "18 500 SEK"
   */
  price: string;
  /**
   * e.g. "incl. VAT · 4 hours"
   */
  priceNote?: string | null;
  features?:
    | {
        text: string;
        id?: string | null;
      }[]
    | null;
  image?: (number | null) | Media;
  ctaLabel?: string | null;
  /**
   * Leave empty to open the contact form with this package selected.
   */
  ctaUrl?: string | null;
  /**
   * The address of this page. Leave empty to generate it from the title.
   */
  slug?: string | null;
  service?: (number | null) | Service;
  mostPopular?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ProcessBlock".
 */
export interface ProcessBlock {
  enabled?: boolean | null;
  tone?: ('light' | 'sand' | 'dark') | null;
  /**
   * Optional ID for links like /#pricing
   */
  anchor?: string | null;
  /**
   * Small label above the heading
   */
  eyebrow?: string | null;
  heading?: string | null;
  /**
   * The steps themselves are managed under Content → Process steps.
   */
  text?: string | null;
  image?: (number | null) | Media;
  id?: string | null;
  blockName?: string | null;
  blockType: 'process';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TestimonialsBlock".
 */
export interface TestimonialsBlock {
  enabled?: boolean | null;
  tone?: ('light' | 'sand' | 'dark') | null;
  /**
   * Optional ID for links like /#pricing
   */
  anchor?: string | null;
  /**
   * Small label above the heading
   */
  eyebrow?: string | null;
  heading?: string | null;
  mode?: ('featured' | 'all' | 'selected') | null;
  testimonials?: (number | Testimonial)[] | null;
  limit?: number | null;
  backgroundImage?: (number | null) | Media;
  id?: string | null;
  blockName?: string | null;
  blockType: 'testimonials';
}
/**
 * Kind words from clients. Drag to reorder.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "testimonials".
 */
export interface Testimonial {
  id: number;
  _order?: string | null;
  /**
   * e.g. "Anna & Erik"
   */
  clientName: string;
  quote: string;
  location?: string | null;
  date?: string | null;
  clientImage?: (number | null) | Media;
  category?: (number | null) | Category;
  /**
   * Show on the homepage.
   */
  featured?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FaqBlock".
 */
export interface FaqBlock {
  enabled?: boolean | null;
  tone?: ('light' | 'sand' | 'dark') | null;
  /**
   * Optional ID for links like /#pricing
   */
  anchor?: string | null;
  /**
   * Small label above the heading
   */
  eyebrow?: string | null;
  heading?: string | null;
  text?: string | null;
  /**
   * Only show questions with this topic (optional).
   */
  topic?: string | null;
  groupByTopic?: boolean | null;
  limit?: number | null;
  cta?: {
    label?: string | null;
    /**
     * e.g. /contact, /portfolio or https://…
     */
    url?: string | null;
  };
  id?: string | null;
  blockName?: string | null;
  blockType: 'faq';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "AvailabilityBlock".
 */
export interface AvailabilityBlock {
  enabled?: boolean | null;
  tone?: ('light' | 'sand' | 'dark') | null;
  /**
   * Optional ID for links like /#pricing
   */
  anchor?: string | null;
  /**
   * Small label above the heading
   */
  eyebrow?: string | null;
  heading?: string | null;
  text?: string | null;
  monthsAhead?: number | null;
  showTentative?: boolean | null;
  cta?: {
    label?: string | null;
    /**
     * e.g. /contact, /portfolio or https://…
     */
    url?: string | null;
  };
  id?: string | null;
  blockName?: string | null;
  blockType: 'availability';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ContactBlock".
 */
export interface ContactBlock {
  enabled?: boolean | null;
  tone?: ('light' | 'sand' | 'dark') | null;
  /**
   * Optional ID for links like /#pricing
   */
  anchor?: string | null;
  /**
   * Small label above the heading
   */
  eyebrow?: string | null;
  heading?: string | null;
  text?: string | null;
  image?: (number | null) | Media;
  showDetails?: boolean | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'contact';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "InstagramBlock".
 */
export interface InstagramBlock {
  enabled?: boolean | null;
  tone?: ('light' | 'sand' | 'dark') | null;
  /**
   * Optional ID for links like /#pricing
   */
  anchor?: string | null;
  /**
   * Small label above the heading
   */
  eyebrow?: string | null;
  heading?: string | null;
  source?: ('manual' | 'live') | null;
  images?: (number | Media)[] | null;
  limit?: number | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'instagram';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "AboutBlock".
 */
export interface AboutBlock {
  enabled?: boolean | null;
  tone?: ('light' | 'sand' | 'dark') | null;
  /**
   * Optional ID for links like /#pricing
   */
  anchor?: string | null;
  showExperience?: boolean | null;
  showPhilosophy?: boolean | null;
  showPublications?: boolean | null;
  showAwards?: boolean | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'about';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "RichTextBlock".
 */
export interface RichTextBlock {
  enabled?: boolean | null;
  tone?: ('light' | 'sand' | 'dark') | null;
  /**
   * Optional ID for links like /#pricing
   */
  anchor?: string | null;
  heading?: string | null;
  content?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  width?: ('narrow' | 'wide') | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'richText';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ImageBannerBlock".
 */
export interface ImageBannerBlock {
  enabled?: boolean | null;
  tone?: ('light' | 'sand' | 'dark') | null;
  /**
   * Optional ID for links like /#pricing
   */
  anchor?: string | null;
  image: number | Media;
  quote?: string | null;
  attribution?: string | null;
  height?: ('full' | 'tall' | 'medium') | null;
  parallax?: boolean | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'imageBanner';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CtaBlock".
 */
export interface CtaBlock {
  enabled?: boolean | null;
  tone?: ('light' | 'sand' | 'dark') | null;
  /**
   * Optional ID for links like /#pricing
   */
  anchor?: string | null;
  /**
   * Small label above the heading
   */
  eyebrow?: string | null;
  heading?: string | null;
  text?: string | null;
  button?: {
    label?: string | null;
    /**
     * e.g. /contact, /portfolio or https://…
     */
    url?: string | null;
  };
  /**
   * Optional background photograph
   */
  image?: (number | null) | Media;
  id?: string | null;
  blockName?: string | null;
  blockType: 'cta';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "PortfolioIndexBlock".
 */
export interface PortfolioIndexBlock {
  enabled?: boolean | null;
  tone?: ('light' | 'sand' | 'dark') | null;
  /**
   * Optional ID for links like /#pricing
   */
  anchor?: string | null;
  showCategoryFilter?: boolean | null;
  limit?: number | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'portfolioIndex';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "JournalListBlock".
 */
export interface JournalListBlock {
  enabled?: boolean | null;
  tone?: ('light' | 'sand' | 'dark') | null;
  /**
   * Optional ID for links like /#pricing
   */
  anchor?: string | null;
  /**
   * Small label above the heading
   */
  eyebrow?: string | null;
  heading?: string | null;
  limit?: number | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'journalList';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "GalleryBlock".
 */
export interface GalleryBlock {
  enabled?: boolean | null;
  tone?: ('light' | 'sand' | 'dark') | null;
  /**
   * Optional ID for links like /#pricing
   */
  anchor?: string | null;
  /**
   * Small label above the heading
   */
  eyebrow?: string | null;
  heading?: string | null;
  images: (number | Media)[];
  id?: string | null;
  blockName?: string | null;
  blockType: 'gallery';
}
/**
 * Drag to reorder. Use topics to group questions.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "faqs".
 */
export interface Faq {
  id: number;
  _order?: string | null;
  question: string;
  answer: string;
  /**
   * Category, e.g. "Booking", "Weddings", "Delivery".
   */
  topic?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * The steps of working with you. Numbers (01, 02…) follow the order — drag to reorder.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "process-steps".
 */
export interface ProcessStep {
  id: number;
  _order?: string | null;
  title: string;
  text?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Tip: the visual “Availability calendar” in the sidebar is the easiest way to manage dates.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "availability".
 */
export interface Availability {
  id: number;
  date: string;
  status: 'booked' | 'tentative' | 'available';
  /**
   * Optional, shown publicly (e.g. "Gotland").
   */
  label?: string | null;
  /**
   * Only visible in the admin panel — never on the website.
   */
  note?: string | null;
  title?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Messages sent from the contact form. Use filters and search, change the status as you go.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "inquiries".
 */
export interface Inquiry {
  id: number;
  name: string;
  email: string;
  phone?: string | null;
  service?: string | null;
  package?: string | null;
  eventDate?: string | null;
  location?: string | null;
  budget?: string | null;
  hours?: string | null;
  message?: string | null;
  /**
   * Private notes — call logs, follow-ups, details.
   */
  internalNotes?:
    | {
        note: string;
        date?: string | null;
        id?: string | null;
      }[]
    | null;
  status: 'new' | 'contacted' | 'follow-up' | 'booked' | 'declined' | 'archived';
  consent?: boolean | null;
  sourcePage?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Write articles, save drafts, publish now or schedule for later.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts".
 */
export interface Post {
  id: number;
  title: string;
  /**
   * Short summary for the journal list and Google.
   */
  excerpt?: string | null;
  cover?: (number | null) | Media;
  content?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  meta?: {
    title?: string | null;
    description?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Media;
    /**
     * Defaults to the meta title.
     */
    ogTitle?: string | null;
    /**
     * Defaults to the meta description.
     */
    ogDescription?: string | null;
    /**
     * Only if this content lives primarily at another address. Leave empty normally.
     */
    canonical?: string | null;
    noIndex?: boolean | null;
  };
  /**
   * The address of this page. Leave empty to generate it from the title.
   */
  slug?: string | null;
  publishedAt?: string | null;
  categories?: (number | PostCategory)[] | null;
  tags?: string[] | null;
  author?: (number | null) | User;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "post-categories".
 */
export interface PostCategory {
  id: number;
  title: string;
  /**
   * The address of this page. Leave empty to generate it from the title.
   */
  slug?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name: string;
  role: 'admin' | 'editor';
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  resetPasswordRequestedAt?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs".
 */
export interface PayloadJob {
  id: number;
  /**
   * Input data provided to the job
   */
  input?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  taskStatus?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  completedAt?: string | null;
  totalTried?: number | null;
  /**
   * If hasError is true this job will not be retried
   */
  hasError?: boolean | null;
  /**
   * If hasError is true, this is the error that caused it
   */
  error?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Task execution log
   */
  log?:
    | {
        executedAt: string;
        completedAt: string;
        taskSlug: 'inline' | 'schedulePublish';
        taskID: string;
        input?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        output?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        state: 'failed' | 'succeeded';
        error?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        id?: string | null;
      }[]
    | null;
  taskSlug?: ('inline' | 'schedulePublish') | null;
  queue?: string | null;
  waitUntil?: string | null;
  processing?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'pages';
        value: number | Page;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'testimonials';
        value: number | Testimonial;
      } | null)
    | ({
        relationTo: 'faqs';
        value: number | Faq;
      } | null)
    | ({
        relationTo: 'process-steps';
        value: number | ProcessStep;
      } | null)
    | ({
        relationTo: 'projects';
        value: number | Project;
      } | null)
    | ({
        relationTo: 'categories';
        value: number | Category;
      } | null)
    | ({
        relationTo: 'services';
        value: number | Service;
      } | null)
    | ({
        relationTo: 'packages';
        value: number | Package;
      } | null)
    | ({
        relationTo: 'availability';
        value: number | Availability;
      } | null)
    | ({
        relationTo: 'inquiries';
        value: number | Inquiry;
      } | null)
    | ({
        relationTo: 'posts';
        value: number | Post;
      } | null)
    | ({
        relationTo: 'post-categories';
        value: number | PostCategory;
      } | null)
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'payload-folders';
        value: number | FolderInterface;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  title?: T;
  layout?:
    | T
    | {
        hero?: T | HeroBlockSelect<T>;
        pageHeader?: T | PageHeaderBlockSelect<T>;
        intro?: T | IntroBlockSelect<T>;
        featuredPortfolio?: T | FeaturedPortfolioBlockSelect<T>;
        featuredStory?: T | FeaturedStoryBlockSelect<T>;
        services?: T | ServicesBlockSelect<T>;
        pricing?: T | PricingBlockSelect<T>;
        process?: T | ProcessBlockSelect<T>;
        testimonials?: T | TestimonialsBlockSelect<T>;
        faq?: T | FaqBlockSelect<T>;
        availability?: T | AvailabilityBlockSelect<T>;
        contact?: T | ContactBlockSelect<T>;
        instagram?: T | InstagramBlockSelect<T>;
        about?: T | AboutBlockSelect<T>;
        richText?: T | RichTextBlockSelect<T>;
        imageBanner?: T | ImageBannerBlockSelect<T>;
        cta?: T | CtaBlockSelect<T>;
        portfolioIndex?: T | PortfolioIndexBlockSelect<T>;
        journalList?: T | JournalListBlockSelect<T>;
        gallery?: T | GalleryBlockSelect<T>;
      };
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
        ogTitle?: T;
        ogDescription?: T;
        canonical?: T;
        noIndex?: T;
      };
  slug?: T;
  excludeFromSitemap?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "HeroBlock_select".
 */
export interface HeroBlockSelect<T extends boolean = true> {
  enabled?: T;
  tone?: T;
  anchor?: T;
  slides?: T;
  eyebrow?: T;
  heading?: T;
  subheading?: T;
  primaryCta?:
    | T
    | {
        label?: T;
        url?: T;
      };
  secondaryCta?:
    | T
    | {
        label?: T;
        url?: T;
      };
  height?: T;
  overlay?: T;
  interval?: T;
  showScrollIndicator?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "PageHeaderBlock_select".
 */
export interface PageHeaderBlockSelect<T extends boolean = true> {
  enabled?: T;
  tone?: T;
  anchor?: T;
  eyebrow?: T;
  heading?: T;
  text?: T;
  image?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "IntroBlock_select".
 */
export interface IntroBlockSelect<T extends boolean = true> {
  enabled?: T;
  tone?: T;
  anchor?: T;
  eyebrow?: T;
  heading?: T;
  text?: T;
  image?: T;
  secondaryImage?: T;
  cta?:
    | T
    | {
        label?: T;
        url?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FeaturedPortfolioBlock_select".
 */
export interface FeaturedPortfolioBlockSelect<T extends boolean = true> {
  enabled?: T;
  tone?: T;
  anchor?: T;
  eyebrow?: T;
  heading?: T;
  text?: T;
  mode?: T;
  projects?: T;
  category?: T;
  limit?: T;
  showCategories?: T;
  cta?:
    | T
    | {
        label?: T;
        url?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FeaturedStoryBlock_select".
 */
export interface FeaturedStoryBlockSelect<T extends boolean = true> {
  enabled?: T;
  tone?: T;
  anchor?: T;
  eyebrow?: T;
  project?: T;
  headingOverride?: T;
  textOverride?: T;
  imageCount?: T;
  ctaLabel?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ServicesBlock_select".
 */
export interface ServicesBlockSelect<T extends boolean = true> {
  enabled?: T;
  tone?: T;
  anchor?: T;
  eyebrow?: T;
  heading?: T;
  text?: T;
  mode?: T;
  services?: T;
  cta?:
    | T
    | {
        label?: T;
        url?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "PricingBlock_select".
 */
export interface PricingBlockSelect<T extends boolean = true> {
  enabled?: T;
  tone?: T;
  anchor?: T;
  eyebrow?: T;
  heading?: T;
  text?: T;
  mode?: T;
  packages?: T;
  footnote?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ProcessBlock_select".
 */
export interface ProcessBlockSelect<T extends boolean = true> {
  enabled?: T;
  tone?: T;
  anchor?: T;
  eyebrow?: T;
  heading?: T;
  text?: T;
  image?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TestimonialsBlock_select".
 */
export interface TestimonialsBlockSelect<T extends boolean = true> {
  enabled?: T;
  tone?: T;
  anchor?: T;
  eyebrow?: T;
  heading?: T;
  mode?: T;
  testimonials?: T;
  limit?: T;
  backgroundImage?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FaqBlock_select".
 */
export interface FaqBlockSelect<T extends boolean = true> {
  enabled?: T;
  tone?: T;
  anchor?: T;
  eyebrow?: T;
  heading?: T;
  text?: T;
  topic?: T;
  groupByTopic?: T;
  limit?: T;
  cta?:
    | T
    | {
        label?: T;
        url?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "AvailabilityBlock_select".
 */
export interface AvailabilityBlockSelect<T extends boolean = true> {
  enabled?: T;
  tone?: T;
  anchor?: T;
  eyebrow?: T;
  heading?: T;
  text?: T;
  monthsAhead?: T;
  showTentative?: T;
  cta?:
    | T
    | {
        label?: T;
        url?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ContactBlock_select".
 */
export interface ContactBlockSelect<T extends boolean = true> {
  enabled?: T;
  tone?: T;
  anchor?: T;
  eyebrow?: T;
  heading?: T;
  text?: T;
  image?: T;
  showDetails?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "InstagramBlock_select".
 */
export interface InstagramBlockSelect<T extends boolean = true> {
  enabled?: T;
  tone?: T;
  anchor?: T;
  eyebrow?: T;
  heading?: T;
  source?: T;
  images?: T;
  limit?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "AboutBlock_select".
 */
export interface AboutBlockSelect<T extends boolean = true> {
  enabled?: T;
  tone?: T;
  anchor?: T;
  showExperience?: T;
  showPhilosophy?: T;
  showPublications?: T;
  showAwards?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "RichTextBlock_select".
 */
export interface RichTextBlockSelect<T extends boolean = true> {
  enabled?: T;
  tone?: T;
  anchor?: T;
  heading?: T;
  content?: T;
  width?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ImageBannerBlock_select".
 */
export interface ImageBannerBlockSelect<T extends boolean = true> {
  enabled?: T;
  tone?: T;
  anchor?: T;
  image?: T;
  quote?: T;
  attribution?: T;
  height?: T;
  parallax?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CtaBlock_select".
 */
export interface CtaBlockSelect<T extends boolean = true> {
  enabled?: T;
  tone?: T;
  anchor?: T;
  eyebrow?: T;
  heading?: T;
  text?: T;
  button?:
    | T
    | {
        label?: T;
        url?: T;
      };
  image?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "PortfolioIndexBlock_select".
 */
export interface PortfolioIndexBlockSelect<T extends boolean = true> {
  enabled?: T;
  tone?: T;
  anchor?: T;
  showCategoryFilter?: T;
  limit?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "JournalListBlock_select".
 */
export interface JournalListBlockSelect<T extends boolean = true> {
  enabled?: T;
  tone?: T;
  anchor?: T;
  eyebrow?: T;
  heading?: T;
  limit?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "GalleryBlock_select".
 */
export interface GalleryBlockSelect<T extends boolean = true> {
  enabled?: T;
  tone?: T;
  anchor?: T;
  eyebrow?: T;
  heading?: T;
  images?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  title?: T;
  caption?: T;
  description?: T;
  blurDataURL?: T;
  _objectKey?: T;
  folder?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumb?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        medium?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        large?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        og?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "testimonials_select".
 */
export interface TestimonialsSelect<T extends boolean = true> {
  _order?: T;
  clientName?: T;
  quote?: T;
  location?: T;
  date?: T;
  clientImage?: T;
  category?: T;
  featured?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "faqs_select".
 */
export interface FaqsSelect<T extends boolean = true> {
  _order?: T;
  question?: T;
  answer?: T;
  topic?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "process-steps_select".
 */
export interface ProcessStepsSelect<T extends boolean = true> {
  _order?: T;
  title?: T;
  text?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "projects_select".
 */
export interface ProjectsSelect<T extends boolean = true> {
  _order?: T;
  title?: T;
  location?: T;
  date?: T;
  excerpt?: T;
  cover?: T;
  gallery?: T;
  chapters?:
    | T
    | {
        heading?: T;
        text?: T;
        afterImage?: T;
        id?: T;
      };
  credits?:
    | T
    | {
        role?: T;
        name?: T;
        id?: T;
      };
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
        ogTitle?: T;
        ogDescription?: T;
        canonical?: T;
        noIndex?: T;
      };
  slug?: T;
  category?: T;
  featured?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories_select".
 */
export interface CategoriesSelect<T extends boolean = true> {
  _order?: T;
  title?: T;
  eyebrow?: T;
  description?: T;
  cover?: T;
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
        ogTitle?: T;
        ogDescription?: T;
        canonical?: T;
        noIndex?: T;
      };
  slug?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "services_select".
 */
export interface ServicesSelect<T extends boolean = true> {
  _order?: T;
  title?: T;
  excerpt?: T;
  image?: T;
  startingPrice?: T;
  priceNote?: T;
  description?: T;
  features?:
    | T
    | {
        text?: T;
        id?: T;
      };
  gallery?: T;
  relatedCategory?: T;
  areas?:
    | T
    | {
        name?: T;
        id?: T;
      };
  ctaLabel?: T;
  ctaUrl?: T;
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
        ogTitle?: T;
        ogDescription?: T;
        canonical?: T;
        noIndex?: T;
      };
  slug?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "packages_select".
 */
export interface PackagesSelect<T extends boolean = true> {
  _order?: T;
  name?: T;
  tagline?: T;
  description?: T;
  price?: T;
  priceNote?: T;
  features?:
    | T
    | {
        text?: T;
        id?: T;
      };
  image?: T;
  ctaLabel?: T;
  ctaUrl?: T;
  slug?: T;
  service?: T;
  mostPopular?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "availability_select".
 */
export interface AvailabilitySelect<T extends boolean = true> {
  date?: T;
  status?: T;
  label?: T;
  note?: T;
  title?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "inquiries_select".
 */
export interface InquiriesSelect<T extends boolean = true> {
  name?: T;
  email?: T;
  phone?: T;
  service?: T;
  package?: T;
  eventDate?: T;
  location?: T;
  budget?: T;
  hours?: T;
  message?: T;
  internalNotes?:
    | T
    | {
        note?: T;
        date?: T;
        id?: T;
      };
  status?: T;
  consent?: T;
  sourcePage?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts_select".
 */
export interface PostsSelect<T extends boolean = true> {
  title?: T;
  excerpt?: T;
  cover?: T;
  content?: T;
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
        ogTitle?: T;
        ogDescription?: T;
        canonical?: T;
        noIndex?: T;
      };
  slug?: T;
  publishedAt?: T;
  categories?: T;
  tags?: T;
  author?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "post-categories_select".
 */
export interface PostCategoriesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  role?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  resetPasswordRequestedAt?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs_select".
 */
export interface PayloadJobsSelect<T extends boolean = true> {
  input?: T;
  taskStatus?: T;
  completedAt?: T;
  totalTried?: T;
  hasError?: T;
  error?: T;
  log?:
    | T
    | {
        executedAt?: T;
        completedAt?: T;
        taskSlug?: T;
        taskID?: T;
        input?: T;
        output?: T;
        state?: T;
        error?: T;
        id?: T;
      };
  taskSlug?: T;
  queue?: T;
  waitUntil?: T;
  processing?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-folders_select".
 */
export interface PayloadFoldersSelect<T extends boolean = true> {
  name?: T;
  folder?: T;
  documentsAndFolders?: T;
  folderType?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings".
 */
export interface SiteSetting {
  id: number;
  siteName: string;
  /**
   * e.g. "Wedding & portrait photographer"
   */
  tagline?: string | null;
  logo?: (number | null) | Media;
  /**
   * Square image, at least 512×512
   */
  favicon?: (number | null) | Media;
  /**
   * Use {year} for the current year, e.g. "© {year} RB Studio"
   */
  copyright?: string | null;
  email?: string | null;
  phone?: string | null;
  /**
   * Where new inquiry notifications are sent (defaults to the email above).
   */
  inquiryEmail?: string | null;
  autoReplyEnabled?: boolean | null;
  autoReplySubject?: string | null;
  /**
   * Use {name} for the client name.
   */
  autoReplyText?: string | null;
  /**
   * Short text shown above the form.
   */
  formIntro?: string | null;
  budgetOptions?:
    | {
        label: string;
        id?: string | null;
      }[]
    | null;
  hoursOptions?:
    | {
        label: string;
        id?: string | null;
      }[]
    | null;
  consentText?: string | null;
  successHeading?: string | null;
  successMessage?: string | null;
  headerLinks?:
    | {
        label: string;
        /**
         * e.g. /portfolio
         */
        url: string;
        id?: string | null;
      }[]
    | null;
  headerCtaLabel?: string | null;
  headerCtaUrl?: string | null;
  footerHeading?: string | null;
  footerText?: string | null;
  footerLinks?:
    | {
        label: string;
        /**
         * e.g. /portfolio
         */
        url: string;
        id?: string | null;
      }[]
    | null;
  legalLinks?:
    | {
        label: string;
        /**
         * e.g. /portfolio
         */
        url: string;
        id?: string | null;
      }[]
    | null;
  social?:
    | {
        platform: 'instagram' | 'facebook' | 'youtube' | 'tiktok' | 'pinterest' | 'linkedin' | 'vimeo' | 'other';
        url: string;
        id?: string | null;
      }[]
    | null;
  /**
   * e.g. @rbstudio
   */
  instagramHandle?: string | null;
  /**
   * For a live feed: a long-lived token from the Instagram API with Instagram Login (professional account). Leave empty to use hand-picked images.
   */
  instagramToken?: string | null;
  seoTitle?: string | null;
  /**
   * Added after every page title.
   */
  seoTitleSuffix?: string | null;
  seoDescription?: string | null;
  ogImage?: (number | null) | Media;
  photographerName?: string | null;
  priceRange?: string | null;
  street?: string | null;
  postalCode?: string | null;
  city?: string | null;
  region?: string | null;
  /**
   * Country code, e.g. SE
   */
  country?: string | null;
  latitude?: number | null;
  longitude?: number | null;
  serviceAreas?:
    | {
        name: string;
        id?: string | null;
      }[]
    | null;
  cookieBannerEnabled?: boolean | null;
  cookieText?: string | null;
  cookiePolicyUrl?: string | null;
  /**
   * G-XXXXXXX (loads only after consent)
   */
  ga4Id?: string | null;
  gtmId?: string | null;
  /**
   * Marketing — loads only after consent
   */
  metaPixelId?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Your personal profile — used on the About page, the homepage introduction and for Google.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "about".
 */
export interface About {
  id: number;
  name: string;
  /**
   * e.g. "Photographer & founder"
   */
  role?: string | null;
  /**
   * e.g. "Based in Stockholm, available worldwide"
   */
  location?: string | null;
  portrait?: (number | null) | Media;
  secondaryImage?: (number | null) | Media;
  /**
   * Large heading on the About page
   */
  headline?: string | null;
  bio?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  philosophy?: string | null;
  style?: string | null;
  /**
   * e.g. "12" / "years behind the camera"
   */
  experience?:
    | {
        value: string;
        label: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Small personal details, e.g. "Coffee" / "Oat flat white"
   */
  facts?:
    | {
        label: string;
        value: string;
        id?: string | null;
      }[]
    | null;
  publications?:
    | {
        name: string;
        year?: string | null;
        url?: string | null;
        id?: string | null;
      }[]
    | null;
  awards?:
    | {
        name: string;
        issuer?: string | null;
        year?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  siteName?: T;
  tagline?: T;
  logo?: T;
  favicon?: T;
  copyright?: T;
  email?: T;
  phone?: T;
  inquiryEmail?: T;
  autoReplyEnabled?: T;
  autoReplySubject?: T;
  autoReplyText?: T;
  formIntro?: T;
  budgetOptions?:
    | T
    | {
        label?: T;
        id?: T;
      };
  hoursOptions?:
    | T
    | {
        label?: T;
        id?: T;
      };
  consentText?: T;
  successHeading?: T;
  successMessage?: T;
  headerLinks?:
    | T
    | {
        label?: T;
        url?: T;
        id?: T;
      };
  headerCtaLabel?: T;
  headerCtaUrl?: T;
  footerHeading?: T;
  footerText?: T;
  footerLinks?:
    | T
    | {
        label?: T;
        url?: T;
        id?: T;
      };
  legalLinks?:
    | T
    | {
        label?: T;
        url?: T;
        id?: T;
      };
  social?:
    | T
    | {
        platform?: T;
        url?: T;
        id?: T;
      };
  instagramHandle?: T;
  instagramToken?: T;
  seoTitle?: T;
  seoTitleSuffix?: T;
  seoDescription?: T;
  ogImage?: T;
  photographerName?: T;
  priceRange?: T;
  street?: T;
  postalCode?: T;
  city?: T;
  region?: T;
  country?: T;
  latitude?: T;
  longitude?: T;
  serviceAreas?:
    | T
    | {
        name?: T;
        id?: T;
      };
  cookieBannerEnabled?: T;
  cookieText?: T;
  cookiePolicyUrl?: T;
  ga4Id?: T;
  gtmId?: T;
  metaPixelId?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "about_select".
 */
export interface AboutSelect<T extends boolean = true> {
  name?: T;
  role?: T;
  location?: T;
  portrait?: T;
  secondaryImage?: T;
  headline?: T;
  bio?: T;
  philosophy?: T;
  style?: T;
  experience?:
    | T
    | {
        value?: T;
        label?: T;
        id?: T;
      };
  facts?:
    | T
    | {
        label?: T;
        value?: T;
        id?: T;
      };
  publications?:
    | T
    | {
        name?: T;
        year?: T;
        url?: T;
        id?: T;
      };
  awards?:
    | T
    | {
        name?: T;
        issuer?: T;
        year?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TaskSchedulePublish".
 */
export interface TaskSchedulePublish {
  input: {
    type?: ('publish' | 'unpublish') | null;
    locale?: string | null;
    doc?: {
      relationTo: 'posts';
      value: number | Post;
    } | null;
    global?: string | null;
    user?: {
      relationTo: 'users';
      value: number | User;
    } | null;
  };
  output?: unknown;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}